# The URL the site will be built for
base_url = "https://thehuglet.github.io"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

title = "thehuglet.github.io"
theme = "terminimal"

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = false

[extra]
accent_color = "orange"
background_color = "dark"
logo_text = "thehuglet.github.io"
author = "thehuglet"

menu_items = [
    {name = "projects", url = "$BASE_URL/pages/projects"},
    {name = "about", url = "$BASE_URL/pages/about"},
    {name = "hire-me", url = "$BASE_URL/pages/hire-me"},
]
